services: 
  frontend:
    image: mihna123/numbers-front
    build: ./frontend/
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: mihna123/numbers-back
    build: ./backend/
    ports: 
      - "8080:8080"


